---

  - name: Install some packages (apt)
    apt: name={{ item }} state=present update_cache=yes
    with_items:
      - ruby
      - git
    when: ansible_os_family == "Debian"

  - name: Install some packages (yum)
    yum: name={{ item }} state=present update_cache=yes
    with_items:
      - ruby
      - git
    when: ansible_os_family == "RedHat"

  - name: Include Debian8 tasks
    include: debian8.yml
    when: ansible_distribution == 'Debian' and ansible_distribution_version == '7'

  - name: Include rh7/centos7 tasks
    include: rh7.yml
    when:  (ansible_distribution == "CentOS" and ansible_distribution_major_version == '7') or (ansible_distribution == "RedHat" and ansible_distribution_major_version == '7')

  - name: Include Ubuntu14 tasks
    include: ubuntu14.yml
    when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '14'

  - name: Include Ubuntu16 tasks
    include: ubuntu16.yml
    when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '16'


