---

  - name: Download chefDK (Ubuntu14)
    get_url:
      url: https://packages.chef.io/files/stable/chefdk/2.0.28/ubuntu/14.04/chefdk_2.0.28-1_amd64.deb
      dest: /opt/chefdk_2.0.28-1_amd64.deb
      checksum: sha256:4fa0daa3f26545a3b4ad104370e210df0d3d909298b2df85a613f564e0780730
      timeout: 30

  -
