--- ### Installs chef

- hosts: all
  gather_facts: False
  become: yes

  pre_tasks:
    - name: Install python for Ansible (only Ubuntu16 issue)
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False
    - setup: 

  roles:
    - change_hostname
    - chef_install

